### ISSUE TITLE
plBindAPI.AutoBinder.pas not under git

### ISSUE THREAD

**Issue by Gronfi** [pmoitaly/BindAPI#2]
Hi, the plBindAPI.AutoBinder.pas is not in the repo.

Regards

**Comment by pmoitaly** [comment]
Hi, 
Thank you very much for your ticket. I have just updated master and 0.8 branch.
Kind regards

Paolo

**Comment by pmoitaly** [comment]
As there was no feedback, I assume this issue is solved. Feel free to open another ticket if the problem is still present.
